apiVersion: 1

notifiers:
  - name: email-alerts
    type: email
    uid: email1
    org_id: 1
    is_default: true
    settings:
      addresses: "admin@yourdomain.com"
      singleEmail: true

  - name: slack-alerts
    type: slack
    uid: slack1
    org_id: 1
    is_default: false
    settings:
      url: "https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL"
      recipient: "#alerts"
      mentionChannel: "here"
      token: "${SLACK_TOKEN}"

  - name: pagerduty-alerts
    type: pagerduty
    uid: pagerduty1
    org_id: 1
    is_default: false
    settings:
      integrationKey: "${PAGERDUTY_KEY}"
      severity: "critical" 